name: Test action in marketplace
on: [workflow_dispatch]

jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - name: Run my own container action
        id: acion
        uses: SmashPlusUltra/MyActionInAction@v1.0.0
        with:
          who-to-greet: '@wulfland'

      - name: Output the answer
        run: echo "teh answer is ${{steps.action.outputs.answer}}
